### ISSUE TITLE
Can't create team from Web UI

### ISSUE THREAD

**Issue by It4lik** [SUSE/Portus#1049]
Hi, 

I git cloned Portus yesterday and get an error while wanting to create trams from the WebUI.
When I use the "Add" button to create a team, nothing happens.

Here are my Unicorn server logs regargind this issue : 
_(I replaced my private ip with the "my_private_ip" string)_
```
Started POST "/portus/teams" for my_private_ip at 2016-08-30 11:22:34 +0200
Cannot render console from my_private_ip! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by TeamsController#create as JS
  Parameters: {"utf8"=>"✓", "team"=>{"name"=>"myteam", "description"=>"my team"}, "commit"=>"Add"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
   (0.1ms)  SELECT COUNT(*) FROM `registries`
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.4ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  lib/portus/config.rb:50:in `block in add_enabled'
  app/policies/team_policy.rb:19:in `create?'
  app/controllers/teams_controller.rb:28:in `create'


  Rendered /rvmhome/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.8ms)
  Rendered /rvmhome/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.5ms)
  Rendered /rvmhome/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.6ms)
  Rendered /rvmhome/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (12.3ms)
```

**Comment by monstermunchkin** [comment]
This seems to be related to #1030.

**Comment by It4lik** [comment]
Yep. I was testing an installation procedure from scratch and I still got the old config.yml... No comment. Sorry for that mate. 

Thank you.
