### ISSUE TITLE
Bundle install without dev and test leads to a broken application

### ISSUE THREAD

**Issue by phaldan** [SUSE/Portus#1100]
Install all ruby dependencies via `bundle install --without test development` leads to following situation:
### Executing `rake db:create`:
```
rake aborted!
LoadError: cannot load such file -- md2man/roff/engine
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/portus/lib/man_pages.rb:1:in `<top (required)>'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/portus/lib/tasks/man.rake:1:in `<top (required)>'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `each'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `run_tasks_blocks'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:452:in `run_tasks_blocks'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:453:in `load_tasks'
/portus/Rakefile:6:in `<top (required)>'
Polyglot::PolyglotLoadError: Failed to load md2man/roff/engine using extensions rb, treetop, tt
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:55:in `load'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:68:in `rescue in require'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/portus/lib/man_pages.rb:1:in `<top (required)>'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/portus/lib/tasks/man.rake:1:in `<top (required)>'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/portus/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `each'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `run_tasks_blocks'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:452:in `run_tasks_blocks'
/portus/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:453:in `load_tasks'
/portus/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```

### Executing `puma`:
```
/bin/sh: puma: not found
```

**Comment by mssola** [comment]
@phaldan #1102 should fix your issue. Regarding puma, this is only meant for development/testing purposes. If you want to also use it in production, you will have to install it manually. We do this because there might be users that like other deployment methods.
