### ISSUE TITLE
Stylesheets not processed correctly

### ISSUE THREAD

**Issue by holgerreif** [SUSE/Portus#1107]
With 2.1.1 I get the following errors from portus-web logs:

```
App 157 stdout: Started GET "/teams/17" for 172.18.18.13 at 2016-10-21 13:04:44 +0000
App 157 stdout: Processing by TeamsController#show as HTML
App 157 stdout:   Parameters: {"id"=>"17"}
App 157 stdout:   Rendered errors/401.html.slim within layouts/errors (0.1ms)
App 157 stdout:   Rendered errors/_status_title.html.slim (0.0ms)
App 157 stdout: Completed 401 Unauthorized in 13ms (Views: 6.9ms | ActiveRecord: 0.7ms)
172.18.18.13 - - [21/Oct/2016:13:04:44 +0000] "GET /teams/17 HTTP/1.1" 401 2980 "https://dockerhub-gui-abn.noncd.rz.db.de/namespaces/17" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"
App 157 stdout: Started GET "/stylesheets/teams.css" for 172.18.18.13 at 2016-10-21 13:04:44 +0000
App 157 stdout:
App 157 stdout: ActionController::RoutingError (No route matches [GET] "/stylesheets/teams.css"):
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/utils.rb:112:in `block in create_thread_and_abort_on_exception'
App 157 stdout:
App 157 stdout:
App 157 stdout: Processing by ErrorsController#show as HTML
App 157 stdout:   Parameters: {"status"=>"404"}
App 157 stdout:   Rendered errors/404.html.slim within layouts/errors (2.4ms)
App 157 stdout:   Rendered errors/_status_title.html.slim (0.0ms)
App 157 stdout: Completed 404 Not Found in 14ms (Views: 13.2ms | ActiveRecord: 0.0ms)
172.18.18.13 - - [21/Oct/2016:13:04:44 +0000] "GET /stylesheets/teams.css HTTP/1.1" 404 2875 "https://dockerhub-gui-abn.noncd.rz.db.de/teams/17" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"
```

```
App 157 stdout: Completed 500 Internal Server Error in 8ms (Views: 7.7ms | ActiveRecord: 0.0ms)
10.180.43.80 - - [25/Oct/2016:05:43:00 +0000] "GET /admin/dashboard HTTP/1.1" 500 2926 "https://dockerhub-gui-abn.noncd.rz.db.de/teams" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0"
App 157 stdout: Started GET "/stylesheets/errors.css" for 10.180.43.80 at 2016-10-25 05:43:00 +0000
App 157 stdout:
App 157 stdout: ActionController::RoutingError (No route matches [GET] "/stylesheets/errors.css"):
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/utils.rb:112:in `block in create_thread_and_abort_on_exception'
App 157 stdout:
App 157 stdout:
App 157 stdout: Processing by ErrorsController#show as HTML
App 157 stdout:   Parameters: {"status"=>"404"}
App 157 stdout:   Rendered errors/404.html.slim within layouts/errors (0.1ms)
App 157 stdout:   Rendered errors/_status_title.html.slim (0.0ms)
App 157 stdout: Completed 404 Not Found in 9ms (Views: 8.7ms | ActiveRecord: 0.0ms)
10.180.43.80 - - [25/Oct/2016:05:43:00 +0000] "GET /stylesheets/errors.css HTTP/1.1" 404 2875 "https://dockerhub-gui-abn.noncd.rz.db.de/admin/dashboard" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0"
```

```
App 157 stdout: Started GET "/namespaces/66" for 10.180.43.47 at 2016-10-25 07:11:43 +0000
App 157 stdout: Processing by NamespacesController#show as HTML
App 157 stdout:   Parameters: {"id"=>"66"}
App 157 stdout:   Rendered errors/401.html.slim within layouts/errors (0.1ms)
App 157 stdout:   Rendered errors/_status_title.html.slim (0.0ms)
App 157 stdout: Completed 401 Unauthorized in 16ms (Views: 7.4ms | ActiveRecord: 1.0ms)
10.180.43.47 - - [25/Oct/2016:07:11:43 +0000] "GET /namespaces/66 HTTP/1.1" 401 2985 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"
10.180.43.47 - - [25/Oct/2016:07:11:43 +0000] "GET /assets/application-308f400bbe270129f3713ed20b11a957.css HTTP/1.1" 304 - "https://dockerhub-gui-abn.noncd.rz.db.de/namespaces/66" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"
App 157 stdout: Started GET "/stylesheets/namespaces.css" for 10.180.43.47 at 2016-10-25 07:11:44 +0000
App 157 stdout:
App 157 stdout: ActionController::RoutingError (No route matches [GET] "/stylesheets/namespaces.css"):
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
App 157 stdout:   vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 157 stdout:   passenger (5.0.18) lib/phusion_passenger/utils.rb:112:in `block in create_thread_and_abort_on_exception'
App 157 stdout:
App 157 stdout:
App 157 stdout: Processing by ErrorsController#show as HTML
App 157 stdout:   Parameters: {"status"=>"404"}
App 157 stdout:   Rendered errors/404.html.slim within layouts/errors (0.1ms)
App 157 stdout:   Rendered errors/_status_title.html.slim (0.1ms)
App 157 stdout: Completed 404 Not Found in 11ms (Views: 10.2ms | ActiveRecord: 0.0ms)
10.180.43.47 - - [25/Oct/2016:07:11:44 +0000] "GET /stylesheets/namespaces.css HTTP/1.1" 404 2875 "https://dockerhub-gui-abn.noncd.rz.db.de/namespaces/66" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"
```

reproduction is easy: as admin try to generate csv activity stream with an undefined activity as in #1104 (case 1) or as normal user try to access via constructed url a team or namespace you are not authorized to access to (case 2 and 3)

**Comment by mssola** [comment]
PR #1114 should fix this
