### ISSUE TITLE
Cron job giving timeout errors

### ISSUE THREAD

**Issue by bweston92** [SUSE/Portus#1284]
Any ideas on the cron job giving this error too?

```
I, [2017-04-25T10:13:44.606806 #6]  INFO -- : Finished CatalogJob in 20.00 seconds
  Crono::CronoJob Load (0.1ms)  SELECT  `crono_jobs`.* FROM `crono_jobs` WHERE `crono_jobs`.`id` = 1 LIMIT 1
I, [2017-04-25T10:23:24.605202 #6]  INFO -- : Perform CatalogJob
  Registry Load (0.1ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1000
Exception: execution expired
I, [2017-04-25T10:23:44.709336 #6]  INFO -- : Finished CatalogJob in 20.10 seconds
  Crono::CronoJob Load (0.2ms)  SELECT  `crono_jobs`.* FROM `crono_jobs` WHERE `crono_jobs`.`id` = 1 LIMIT 1
I, [2017-04-25T10:33:24.605722 #6]  INFO -- : Perform CatalogJob
  Registry Load (0.1ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1000
Exception: execution expired
```

Running `bundle exec rails r bin/client.rb catalog` produces:

```
[Mailer config] Host:     portus.legalweb.tech
[Mailer config] Protocol: http://
  Registry Load (0.1ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
/usr/local/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/local/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/local/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /portus/lib/portus/http_helpers.rb:147:in `get_response_token'
	from /portus/lib/portus/http_helpers.rb:43:in `perform_request'
	from /portus/lib/portus/registry_client.rb:113:in `get_page'
	from /portus/lib/portus/registry_client.rb:100:in `paged_response'
	from /portus/lib/portus/registry_client.rb:66:in `catalog'
	from bin/client.rb:41:in `<top (required)>'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/runner.rb:60:in `load'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'

```

**Comment by bweston92** [comment]
Sorry turned out to be a DNS issue in the containers.
