### ISSUE TITLE
Clair security backend throwing 500 when Layer missing Features key

### ISSUE THREAD

**Issue by jamesmaidment** [SUSE/Portus#1351]
Example layer:
```
{"Name"=>"sha256:d68f678e277bd65f0bd0aa498c2864083be4a9b7143b632b4440954ac6641de4", "ParentName"=>"sha256:5884a61ab3a9db3cd3591bf46811639a8497112edaf7d7288f0d8f72ea828a2d", "IndexedByVersion"=>3}
```
Error message:
```
Started POST "/v2/webhooks/events" for 172.18.0.1 at 2017-07-28 15:08:25 +0000
Processing by Api::V2::EventsController#create as JSON
Completed 202 Accepted in 1ms (ActiveRecord: 0.0ms)
2017-07-28 15:08:25 +0000: SSL error, peer: 172.18.0.1, peer cert: , #<Puma::MiniSSL::SSLError: System error: Success - 0>
Completed 500 Internal Server Error in 483ms (ActiveRecord: 7.2ms)

NoMethodError (undefined method `each' for nil:NilClass):
  lib/portus/security_backends/clair.rb:45:in `layer_vulnerabilities'
  lib/portus/security_backends/clair.rb:30:in `vulnerabilities'
  lib/portus/security.rb:48:in `block in vulnerabilities'
  lib/portus/security.rb:46:in `each'
  lib/portus/security.rb:46:in `vulnerabilities'
  app/models/tag.rb:96:in `vulnerabilities'
  app/models/tag.rb:90:in `block in as_json'
  app/models/tag.rb:89:in `tap'
  app/models/tag.rb:89:in `as_json'
  app/controllers/repositories_controller.rb:19:in `show'

Processing by ErrorsController#show as JSON
  Parameters: {"id"=>"4", "status"=>"500"}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim]}. Searched in:
  * "/srv/Portus/app/views"
  * "/usr/local/bundle/gems/kaminari-0.16.3/app/views"
  * "/usr/local/bundle/gems/devise-3.5.1/app/views"
   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/path_set.rb:46:in `find'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/lookup_context.rb:121:in `find'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:8:in `render'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /srv/Portus/app/controllers/errors_controller.rb:15:in `show'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/local/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  /usr/local/bundle/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
  /usr/local/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
  /usr/local/bundle/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
  /usr/local/bundle/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  /usr/local/bundle/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
  /usr/local/bundle/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
  /usr/local/bundle/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
  /usr/local/bundle/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
  /usr/local/bundle/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
  /usr/local/bundle/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I'm happy to submit a patch to check the Layer for the Feature key.

**Comment by jamesmaidment** [comment]
PR: https://github.com/SUSE/Portus/pull/1352
