### ISSUE TITLE
Clair result in 500 error.

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1405]
Trying to integrate clair with portus, this is what I get. Not sure if its related to #1378 

```
portus_1              | Started GET "/repositories/2.json" for 84.72.104.165 at 2017-09-04 19:18:29 +0000
portus_1              | Processing by RepositoriesController#show as JSON
portus_1              |   Parameters: {"id"=>"2"}
registry_1              | time="2017-09-04T19:18:29Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=test.domain.com http.request.id=38762a05-810a-474d-a045-d96c45a0e6ff http.request.method=GET http.request.remoteaddr=163.172.187.116 http.request.uri="/v2/vad1mo/registry/manifests/latest" http.request.useragent=Ruby instance.id=86467a29-aff0-42c7-acac-d85fa0f0fb39 vars.name="vad1mo/registry" vars.reference=latest version=v2.6.2 
registry_1              | 172.18.0.8 - - [04/Sep/2017:19:18:29 +0000] "GET /v2/vad1mo/registry/manifests/latest HTTP/1.1" 401 157 "" "Ruby"
proxy_1                 | 163.172.187.116 - - [04/Sep/2017:19:18:29 +0000] "GET /v2/vad1mo/registry/manifests/latest HTTP/1.1" 401 157 "-" "Ruby"
proxy_1                 | 2017/09/04 19:18:29 [info] 23#23: *462 client 163.172.187.116 closed keepalive connection
portus_1              | Started GET "/v2/token?account=portus&scope=repository%3Avad1mo%2Fregistry%3Apull&service=test.domain.com" for 163.172.187.116 at 2017-09-04 19:18:29 +0000
portus_1              | Processing by Api::V2::TokensController#show as JSON
portus_1              |   Parameters: {"account"=>"portus", "scope"=>"repository:vad1mo/registry:pull", "service"=>"test.domain.com"}
portus_1              | [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.46ms)
portus_1              | Completed 200 OK in 168ms (Views: 2.1ms | ActiveRecord: 18.8ms)
proxy_1                 | 163.172.187.116 - portus [04/Sep/2017:19:18:29 +0000] "GET /v2/token?account=portus&scope=repository%3Avad1mo%2Fregistry%3Apull&service=test.domain.com HTTP/1.1" 200 708 "-" "Ruby"
proxy_1                 | 2017/09/04 19:18:30 [info] 23#23: *465 client 163.172.187.116 closed keepalive connection
registry_1              | time="2017-09-04T19:18:30Z" level=info msg="response completed" go.version=go1.7.6 http.request.host=test.domain.com http.request.id=40485c28-f9b3-4eeb-b3c6-73cf710b1d44 http.request.method=GET http.request.remoteaddr=163.172.187.116 http.request.uri="/v2/vad1mo/registry/manifests/latest" http.request.useragent=Ruby http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=159.452113ms http.response.status=200 http.response.written=2188 instance.id=86467a29-aff0-42c7-acac-d85fa0f0fb39 version=v2.6.2 
registry_1              | 172.18.0.8 - - [04/Sep/2017:19:18:30 +0000] "GET /v2/vad1mo/registry/manifests/latest HTTP/1.1" 200 2188 "" "Ruby"
proxy_1                 | 163.172.187.116 - - [04/Sep/2017:19:18:30 +0000] "GET /v2/vad1mo/registry/manifests/latest HTTP/1.1" 200 2188 "-" "Ruby"
proxy_1                 | 2017/09/04 19:18:30 [info] 23#23: *468 client 163.172.187.116 closed keepalive connection
portus_1              | [active_model_serializers] Rendered ActiveModel::Serializer::Null with Repository (611.3ms)
portus_1              | Started POST "/v2/webhooks/events" for 172.18.0.9 at 2017-09-04 19:18:30 +0000
portus_1              | Completed 500 Internal Server Error in 636ms (ActiveRecord: 7.3ms)
portus_1              | Processing by Api::V2::EventsController#create as JSON
portus_1              | Completed 202 Accepted in 1ms (ActiveRecord: 0.0ms)
portus_1              | 
portus_1              | URI::BadURIError (both URI are relative):
portus_1              |   lib/portus/http_helpers.rb:27:in `get_request'
portus_1              |   lib/portus/security_backends/clair.rb:85:in `post_layer'
portus_1              |   lib/portus/security_backends/clair.rb:26:in `block in vulnerabilities'
portus_1              |   lib/portus/security_backends/clair.rb:26:in `each_index'
portus_1              |   lib/portus/security_backends/clair.rb:26:in `vulnerabilities'
portus_1              |   lib/portus/security.rb:48:in `block in vulnerabilities'
portus_1              |   lib/portus/security.rb:46:in `each'
portus_1              |   lib/portus/security.rb:46:in `vulnerabilities'
portus_1              |   app/models/tag.rb:96:in `vulnerabilities'
portus_1              |   app/models/tag.rb:90:in `block in as_json'
portus_1              |   app/models/tag.rb:89:in `tap'
portus_1              |   app/models/tag.rb:89:in `as_json'
portus_1              |   app/controllers/repositories_controller.rb:19:in `show'
portus_1              |   app/middleware/catch_json_parse_errors.rb:9:in `call'
portus_1              | 
portus_1              | 
portus_1              | Processing by ErrorsController#show as JSON
portus_1              |   Parameters: {"id"=>"2", "status"=>"500"}
portus_1              | Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms)
portus_1              | Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim]}. Searched in:
portus_1              |   * "/portus/app/views"
portus_1              |   * "/usr/local/bundle/gems/kaminari-0.16.3/app/views"
portus_1              |   * "/usr/local/bundle/gems/devise-3.5.1/app/views"
portus_1              | 
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/path_set.rb:46:in `find'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/lookup_context.rb:121:in `find'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:8:in `render'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
portus_1              |   /usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
portus_1              |   /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
portus_1              |   /portus/app/controllers/errors_controller.rb:15:in `show'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
portus_1              |   /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
portus_1              |   /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
proxy_1                 | 84.72.104.165 - - [04/Sep/2017:19:18:30 +0000] "GET /repositories/2.json HTTP/2.0" 500 326 "https://test.domain.com/repositories/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
portus_1              |   /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
portus_1              |   /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
portus_1              |   /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
portus_1              |   /usr/local/bundle/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
portus_1              |   /usr/local/bundle/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
portus_1              |   /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
portus_1              |   /usr/local/bundle/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:140:in `forward'
portus_1              |   /usr/local/bundle/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:249:in `fetch'
portus_1              |   /usr/local/bundle/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:189:in `lookup'
portus_1              |   /usr/local/bundle/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:66:in `call!'
portus_1              |   /usr/local/bundle/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:51:in `call'
portus_1              |   /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
portus_1              |   /usr/local/bundle/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
portus_1              |   /usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
portus_1              |   /usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
portus_1              |   /usr/local/bundle/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
portus_1              |   /usr/local/bundle/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
portus_1              |   /usr/local/bundle/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
portus_1              |   /usr/local/bundle/gems/puma-3.7.0/lib/puma/configuration.rb:226:in `call'
portus_1              |   /usr/local/bundle/gems/puma-3.7.0/lib/puma/server.rb:578:in `handle_request'
portus_1              |   /usr/local/bundle/gems/puma-3.7.0/lib/puma/server.rb:415:in `process_client'
portus_1              |   /usr/local/bundle/gems/puma-3.7.0/lib/puma/server.rb:275:in `block in run'
portus_1              |   /usr/local/bundle/gems/puma-3.7.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by mssola** [comment]
It might. I'll mark this as a bug, and then I'll come to this whenever I go for #1378.

**Comment by mssola** [comment]
Does this still happen to you ? I think this has been fixed for a while 🤔 Note that you cannot use the current master of Clair, since they've changed quite some stuff. You should use the v2 versions of Clair (see the docker-compose.yml file on the root of the project for an example).

**Comment by Vad1mo** [comment]
I'll check it with the latest head in the next days. However a few weeks ago I didn't get a 500 anymore but also I didn't get any vulnerability results.

**Comment by mssola** [comment]
I believe that at first we made sure that Portus didn't crash (maybe that's the version you tried ?), and then we polished a couple of things and pinned the Clair version. Just make sure to use the right version of Clair 😉

**Comment by mssola** [comment]
Moving to the 2.4 milestone (but if this is an issue, we can provide a fix for a patch-level release).
