### ISSUE TITLE
Creating Namespaces results in Error

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1406]
On the latest head: 45014974f3f26944725584b89886b226ecc8f79d when I try to create a new namespace this error is yeld in the logs. 

**(Couldn't find Namespace with 'id'=typeahead):**

This is the ID that was added.
`INSERT INTO `namespaces` (`id`, `name`, `created_at`, `updated_at`, `team_id`, `registry_id`, `global`, `description`, `visibility`)
VALUES
	(7, 'ns4', '2017-09-04 20:10:48', '2017-09-04 20:10:48', 4, 1, 0, 'asdf', 0);
`

In prod mode I get the other **Name has already been taken** but the name is unique. 

Local Log
```
Started POST "/namespaces.json" for 127.0.0.1 at 2017-09-04 22:10:48 +0200
Started POST "/namespaces.json" for 127.0.0.1 at 2017-09-04 22:10:48 +0200
Processing by NamespacesController#create as JSON
Processing by NamespacesController#create as JSON
  Parameters: {"namespace"=>{"name"=>"ns4", "team"=>"a-team", "description"=>"asdf"}}
  Parameters: {"namespace"=>{"name"=>"ns4", "team"=>"a-team", "description"=>"asdf"}}
  User Load (0.8ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
  User Load (0.8ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
   (0.7ms)  SELECT COUNT(*) FROM `registries`
   (0.7ms)  SELECT COUNT(*) FROM `registries`
  Team Load (0.6ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`name` = 'a-team' AND `teams`.`hidden` = 0 LIMIT 1
  Team Load (0.6ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`name` = 'a-team' AND `teams`.`hidden` = 0 LIMIT 1
Unpermitted parameter: team
Unpermitted parameter: team
  Registry Load (0.6ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
  Registry Load (0.6ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
   (1.1ms)  BEGIN
   (1.1ms)  BEGIN
  Namespace Exists (1.5ms)  SELECT  1 AS one FROM `namespaces` WHERE (`namespaces`.`name` = BINARY 'ns4' AND `namespaces`.`registry_id` = 1) LIMIT 1
  Namespace Exists (1.5ms)  SELECT  1 AS one FROM `namespaces` WHERE (`namespaces`.`name` = BINARY 'ns4' AND `namespaces`.`registry_id` = 1) LIMIT 1
  SQL (1.9ms)  INSERT INTO `namespaces` (`team_id`, `name`, `visibility`, `registry_id`, `description`, `created_at`, `updated_at`) VALUES (4, 'ns4', 0, 1, 'asdf', '2017-09-04 20:10:48', '2017-09-04 20:10:48')
  SQL (1.9ms)  INSERT INTO `namespaces` (`team_id`, `name`, `visibility`, `registry_id`, `description`, `created_at`, `updated_at`) VALUES (4, 'ns4', 0, 1, 'asdf', '2017-09-04 20:10:48', '2017-09-04 20:10:48')
   (3.4ms)  COMMIT
   (3.4ms)  COMMIT
   (0.5ms)  BEGIN
   (0.5ms)  BEGIN
  SQL (0.7ms)  INSERT INTO `activities` (`owner_id`, `owner_type`, `key`, `parameters`, `trackable_id`, `trackable_type`, `created_at`, `updated_at`) VALUES (2, 'User', 'namespace.create', '---\n:team: a-team\n', 7, 'Namespace', '2017-09-04 20:10:49', '2017-09-04 20:10:49')
  SQL (0.7ms)  INSERT INTO `activities` (`owner_id`, `owner_type`, `key`, `parameters`, `trackable_id`, `trackable_type`, `created_at`, `updated_at`) VALUES (2, 'User', 'namespace.create', '---\n:team: a-team\n', 7, 'Namespace', '2017-09-04 20:10:49', '2017-09-04 20:10:49')
   (2.3ms)  COMMIT
   (2.3ms)  COMMIT
[active_model_serializers]    (1.0ms)  SELECT COUNT(*) FROM `webhooks` WHERE `webhooks`.`namespace_id` = 7
[active_model_serializers]    (1.0ms)  SELECT COUNT(*) FROM `webhooks` WHERE `webhooks`.`namespace_id` = 7
[active_model_serializers]    (0.8ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 7
[active_model_serializers]    (0.8ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 7
[active_model_serializers] Rendered NamespaceSerializer with ActiveModelSerializers::Adapter::JsonApi (18.49ms)
[active_model_serializers] Rendered NamespaceSerializer with ActiveModelSerializers::Adapter::JsonApi (18.49ms)
Completed 200 OK in 102ms (Views: 18.8ms | ActiveRecord: 18.5ms)
Completed 200 OK in 102ms (Views: 18.8ms | ActiveRecord: 18.5ms)




Started HEAD "/namespaces" for 127.0.0.1 at 2017-09-04 22:10:50 +0200
Started HEAD "/namespaces" for 127.0.0.1 at 2017-09-04 22:10:50 +0200




Started GET "/namespaces/typeahead/" for 127.0.0.1 at 2017-09-04 22:10:50 +0200
Started GET "/namespaces/typeahead/" for 127.0.0.1 at 2017-09-04 22:10:50 +0200
Processing by NamespacesController#index as JSON
Processing by NamespacesController#index as JSON
Processing by NamespacesController#show as JSON
Processing by NamespacesController#show as JSON
  Parameters: {"id"=>"typeahead"}
  Parameters: {"id"=>"typeahead"}
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
   (0.7ms)  SELECT COUNT(*) FROM `registries`
   (0.7ms)  SELECT COUNT(*) FROM `registries`
   (0.9ms)  SELECT COUNT(*) FROM `registries`
   (0.9ms)  SELECT COUNT(*) FROM `registries`
  Namespace Load (1.6ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 0 LIMIT 1
  Namespace Load (1.6ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 0 LIMIT 1
Completed 404 Not Found in 16ms (ActiveRecord: 5.0ms)
Completed 404 Not Found in 16ms (ActiveRecord: 5.0ms)

ActiveRecord::RecordNotFound (Couldn't find Namespace with 'id'=typeahead):
  app/controllers/namespaces_controller.rb:176:in `set_namespace'
  app/middleware/catch_json_parse_errors.rb:9:in `call'



ActiveRecord::RecordNotFound (Couldn't find Namespace with 'id'=typeahead):
  app/controllers/namespaces_controller.rb:176:in `set_namespace'
  app/middleware/catch_json_parse_errors.rb:9:in `call'


  Rendered namespaces/partials/_special_namespaces.html.slim (5.9ms)
  Rendered namespaces/partials/_special_namespaces.html.slim (5.9ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Rendered namespaces/partials/_accessible_namespaces.html.slim (6.8ms)
  Rendered namespaces/partials/_accessible_namespaces.html.slim (6.8ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.1ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.1ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (1.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (1.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (2.1ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (2.1ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (82.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (82.3ms)
  Rendered namespaces/components/_form.html.slim (53.2ms)
  Rendered namespaces/components/_form.html.slim (53.2ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered namespaces/components/_panel.html.slim (4.5ms)
  Rendered namespaces/components/_panel.html.slim (4.5ms)
  Rendered namespaces/components/_table.html.slim (10.6ms)
  Rendered namespaces/components/_table.html.slim (10.6ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered namespaces/components/_table_row.html.slim (5.7ms)
  Rendered namespaces/components/_table_row.html.slim (5.7ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/console.js.erb within layouts/javascript (57.5ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/console.js.erb within layouts/javascript (57.5ms)
  Rendered namespaces/components/_visibility.html.slim (5.9ms)
  Rendered namespaces/components/_visibility.html.slim (5.9ms)
  Rendered namespaces/partials/_components_templates.html.slim (187.8ms)
  Rendered namespaces/partials/_components_templates.html.slim (187.8ms)
  Rendered namespaces/index.html.slim within layouts/application (307.2ms)
  Rendered namespaces/index.html.slim within layouts/application (307.2ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/index.html.erb (132.2ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/index.html.erb (132.2ms)
  Rendered shared/_header.html.slim (7.1ms)
  Rendered shared/_header.html.slim (7.1ms)
  Rendered shared/_aside.html.slim (7.7ms)
  Rendered shared/_aside.html.slim (7.7ms)
  Rendered shared/_search.html.slim (5.1ms)
  Rendered shared/_search.html.slim (5.1ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (6.0ms)
  Rendered shared/_notification.html.slim (6.0ms)
  Rendered shared/_notifications.html.slim (25.1ms)
  Rendered shared/_notifications.html.slim (25.1ms)
Completed 500 Internal Server Error in 504ms (Views: 498.8ms | ActiveRecord: 1.4ms)
Completed 500 Internal Server Error in 504ms (Views: 498.8ms | ActiveRecord: 1.4ms)

Pundit::PolicyScopingNotPerformedError (Pundit::PolicyScopingNotPerformedError):
  app/middleware/catch_json_parse_errors.rb:9:in `call'



Pundit::PolicyScopingNotPerformedError (Pundit::PolicyScopingNotPerformedError):
  app/middleware/catch_json_parse_errors.rb:9:in `call'


  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.8ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.8ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.7ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.7ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.5ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.5ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (37.5ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (37.5ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/console.js.erb within layouts/javascript (41.2ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/console.js.erb within layouts/javascript (41.2ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/index.html.erb (96.6ms)
  Rendered /Users/vad1mo/.rvm/gems/ruby-2.3.3/gems/web-console-2.1.3/lib/web_console/templates/index.html.erb (96.6ms)
```

**Comment by mssola** [comment]
I can reproduce this in current master ...

**Comment by mssola** [comment]
@vitoravelino is it possible that this is an issue from the Vue refactoring ? 😕

**Comment by mssola** [comment]
Moreover, the UI freezes ...

**Comment by vitoravelino** [comment]
That's probably a side effect of the changes I've made recently. I'll take a look later.

**Comment by mssola** [comment]
> That's probably a side effect of the changes I've made recently. I'll take a look later.

Thanks a bunch! 👍

**Comment by vitoravelino** [comment]
I was able to reproduce. Working on it. Nice catch, thanks!
