### ISSUE TITLE
Unknown database 'portus_development' (ActiveRecord::NoDatabaseError)

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1572]
This is a regression bug recently introduced  after 2nd January.

The Vanilla `docker-compose build`and `docker-compuse up` will reproduce this error.

```
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:23:in `rescue in mysql2_connection': Unknown database 'portus_development' (ActiveRecord::NoDatabaseError)
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:9:in `mysql2_connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
portus_1      |         from /usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
portus_1      |         from /usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:139:in `replace_bind_variables'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:128:in `sanitize_sql_array'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:26:in `sanitize_sql_for_conditions'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/relation/query_methods.rb:950:in `build_where'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/relation/query_methods.rb:584:in `where!'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/relation/query_methods.rb:574:in `where'
portus_1      |         from /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:10:in `where'
portus_1      |         from /srv/Portus/app/models/setting.rb:75:in `current_settings'
portus_1      |         from /srv/Portus/config/initializers/01_settings.rb:8:in `<top (required)>'

```

**Comment by mssola** [comment]
This is when using the `docker-compose.yml` file on the root of the project ? or it's one of the examples ? Just saying because the one on the root of the project builds just fine 😕

**Comment by Vad1mo** [comment]
It's in the root, I'll give it a try and see if that is fixed. 

However this only happens if there is no DB.

**Comment by mssola** [comment]
@Vad1mo is this still valid for you ?

**Comment by Vad1mo** [comment]
its fixed now
