### ISSUE TITLE
Creating a production like setup is cumbersome and current files aren't helping.

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1611]
The provided sample inti.rb and puma.rb files in combination with ping, or actually everything that does something like `system("bundle exec..")` is failing in other environments then development.

Reason is everytime system is called env variables aren't passed.(and existing also ignored)

Here you see that after the db is setup the next task fails as the environment variables are missing. 
The current solution is to pass env var top down to all rake tasks but thats not an ideal solution.

```
portus_1    | -- initialize_schema_migrations_table()
portus_1    |    -> 0.0994s
portus_1    | Adding the "admin" user portus
portus_1    | rake aborted!
portus_1    | Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
portus_1    | /app/config/initializers/draw_def.rb:5:in `instance_eval'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:50:in `establish_connection'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/railtie.rb:122:in `block (2 levels) in <class:Railtie>'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/base.rb:26:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /app/app/models/user.rb:40:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:360:in `require_or_load'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:494:in `load_missing_constant'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:184:in `const_missing'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261:in `const_get'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261:in `block in constantize'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `each'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `inject'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `constantize'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:566:in `get'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:597:in `constantize'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise.rb:315:in `get'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:83:in `to'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:78:in `modules'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:95:in `routes'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:162:in `default_used_route'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:72:in `initialize'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise.rb:345:in `new'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise.rb:345:in `add_mapping'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/rails/routes.rb:243:in `block in devise_for'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/rails/routes.rb:242:in `each'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/rails/routes.rb:242:in `devise_for'
portus_1    | (eval):3:in `draw'
portus_1    | /app/config/initializers/draw_def.rb:5:in `instance_eval'
portus_1    | /app/config/initializers/draw_def.rb:5:in `draw'
portus_1    | /app/config/routes.rb:4:in `block (2 levels) in <top (required)>'
portus_1    | /app/config/routes.rb:4:in `each'
portus_1    | /app/config/routes.rb:4:in `block in <top (required)>'
portus_1    | /usr/local/bundle/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
portus_1    | /usr/local/bundle/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
portus_1    | /usr/local/bundle/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:410:in `draw'
portus_1    | /app/config/routes.rb:3:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `each'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `load_paths'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:16:in `reload!'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:26:in `block in updater'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/file_update_checker.rb:75:in `execute'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:27:in `updater'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
portus_1    | /app/config/environment.rb:7:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
portus_1    | /usr/local/bundle/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
portus_1    | /usr/local/bundle/bin/bundle:104:in `load'
portus_1    | /usr/local/bundle/bin/bundle:104:in `<main>'
portus_1    | 
portus_1    | Caused by:
portus_1    | Gem::LoadError: mysql2 is not part of the bundle. Add it to your Gemfile.
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:3:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_adapters/connection_specification.rb:175:in `spec'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:50:in `establish_connection'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/railtie.rb:122:in `block (2 levels) in <class:Railtie>'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
portus_1    | /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/base.rb:26:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /app/app/models/user.rb:40:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:360:in `require_or_load'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:494:in `load_missing_constant'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:184:in `const_missing'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261:in `const_get'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:261:in `block in constantize'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `each'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `inject'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `constantize'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:566:in `get'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:597:in `constantize'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise.rb:315:in `get'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:83:in `to'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:78:in `modules'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:95:in `routes'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:162:in `default_used_route'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/mapping.rb:72:in `initialize'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise.rb:345:in `new'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise.rb:345:in `add_mapping'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/rails/routes.rb:243:in `block in devise_for'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/rails/routes.rb:242:in `each'
portus_1    | /usr/local/bundle/gems/devise-4.4.0/lib/devise/rails/routes.rb:242:in `devise_for'
portus_1    | (eval):3:in `draw'
portus_1    | /app/config/initializers/draw_def.rb:5:in `instance_eval'
portus_1    | /app/config/initializers/draw_def.rb:5:in `draw'
portus_1    | /app/config/routes.rb:4:in `block (2 levels) in <top (required)>'
portus_1    | /app/config/routes.rb:4:in `each'
portus_1    | /app/config/routes.rb:4:in `block in <top (required)>'
portus_1    | /usr/local/bundle/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
portus_1    | /usr/local/bundle/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
portus_1    | /usr/local/bundle/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:410:in `draw'
portus_1    | /app/config/routes.rb:3:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `each'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `load_paths'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:16:in `reload!'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:26:in `block in updater'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/file_update_checker.rb:75:in `execute'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:27:in `updater'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
portus_1    | /app/config/environment.rb:7:in `<top (required)>'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1    | /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
portus_1    | /usr/local/bundle/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
portus_1    | /usr/local/bundle/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
portus_1    | /usr/local/bundle/bin/bundle:104:in `load'
portus_1    | /usr/local/bundle/bin/bundle:104:in `<main>'
portus_1    | Tasks: TOP => db:migrate:status => environment
portus_1    | (See full trace by running task with --trace)
portus_1    | [10] Puma starting in cluster mode...
portus_1    | [10] * Version 3.10.0 (ruby 2.5.0-p0), codename: Russell's Teapot
portus_1    | [10] * Min threads: 0, max threads: 2
portus_1    | [10] * Environment: production
portus_1    | [10] * Process workers: 2
portus_1    | [10] * Preloading application
portus_1    | [Mailer config] Host:     portus.test.lan
portus_1    | [Mailer config] Protocol: https://
^CGracefully stopping... (press Ctrl+C again to force)

```

**Comment by mssola** [comment]
Is this coming from one of the examples ? And note that `bundle` should never be executed on the production environment for Portus (use `portusctl` instead).

**Comment by Vad1mo** [comment]
kind of, I created based on the examples, a production like init.rb and puma.rb however all then env variables are messed and checked everywhere in the application during runtime. 

I think the best idea is to create a bash script the does start pume and not ruby as env vars can't be set.

**Comment by mssola** [comment]
See [my comment](https://github.com/SUSE/Portus/issues/1616#issuecomment-364137294).
