### ISSUE TITLE
Another Authorization token failure for backround.rb 

### ISSUE THREAD

**Issue by Nick-Harvey** [SUSE/Portus#1624]
I thought this might be related to https://github.com/SUSE/Portus/issues/1618 but it doesn't seem to be. 

Running `bundle exec rails r bin/background.rb` in the container returns:

`Exception: Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x0000000006bf14f8>`

logs from the container:
```
Started GET "/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=hub-foobar-registry%3A5000" for XX.XX.XX.XX at 2018-01-24 16:55:35 +0000
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"hub-foobar-registry:5000"}
Completed 401 Unauthorized in 399ms (ActiveRecord: 259.6ms)
```

I've double and triple checked that the portus users password is set correctly and what's strange is if I try to curl it from inside the container auth seems to work:

```
curl -ik --user portus:$PORTUS_PASSWORD  https://hub.foobar.com/v2/token?account=portus\&service=0.0.0.0:5000
HTTP/1.1 200 OK
Server: nginx/1.13.5
Date: Wed, 24 Jan 2018 17:02:16 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
ETag: W/"b829d4f05218e7b72d93db85c44d2cc4"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _portus_session=MlVodFZ3ZmNXWnVmVkc2RUttaUZ4bUVUL2JoYjVsSjJ3dFhkd1VIT3FXNnVKSUpUTm12bGNqeFdQWUtoM2JZeGNGbWtqd1UyZ2w3RTk5ellHL1FZMFE9PS0teVFMd0s5TGlNaDFwUzhXYU42NjU3Zz09--b96130a3684d3500d1e2845e569731dc1ffbbd15; path=/; HttpOnly
X-Request-Id: 707709ac-e3f9-4377-9b03-c2f34c4197d4
X-Runtime: 0.582178
Strict-Transport-Security: max-age=15724800; includeSubDomains;
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-UA-Compatible: IE=edge

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjJPQ0M6TklLUDpOSllXOjdKVkg6V0dGTTpFUzVSOkdWT1c6S1RUUjpQNFFHOkszTjY6TUNSMjpRU0JUIn0.eyJpc3MiOiJodWIucHJvamVjdGljYXJ1cy5haSIsInN1YiI6InBvcnR1cyIsImF1ZCI6IjAuMC4wLjA6NTAwMCIsImlhdCI6MTUxNjgxMzMzNiwibmJmIjoxNTE2ODEzMzMxLCJleHAiOjE1MTY4MTM2MzYsImp0aSI6IkF1N0VQSHdnbnptVTk3ZHFIVnZHU1kxTGRyNXFVNGJLdDFhb2lkR1hNSCIsImFjY2VzcyI6W119.lVgxzvB2vCfvzrGweVlVvoF28GlCSdybRU6eATjgbeuSOIRzrz25ydmRaumh3xz8GKrjsS9JWLCaSE8yuLBuAINqy-qHsfozvf2zyf-kGmtZ37muYsH_dT5IK4CZvSU9zUwvvid9P7kOaeqdovyqj8y9bWAI2zltp0kMvJ68cKb00-ppuvtgtSn19Tacxi_XoHl6hWK9_CHfVhhrEjBVx9R5CX5j6QmABFDLMlihKXWbGwLvgJvE_tW5HweseRlLgmVYHIDySxW-J7megYCPE9RjxAQKtScSaeZcA0KAZS0YBuFy8ols-OVe-CxN3VRsv5-rCaBaYGsvSXq2HqgAmpX8EvWdNyjZe-KEuxh5fAHbXzMgq1NHUXL0P8tUfQesFnbPD3Sw8qf7Cvl6hctg2JgdQ2HnBWxwKR_zKslL3K-2nbRS6WhhEYSwcvDTv3YzNE_2TPSO1omLuOoXPSO60Ey4RdCyZVeYdB95XPf_1ZkkiZd-bLAUn91WaayPCAYl","expires_in":300,"issued_at":"2018-01-24T17:02:16+00:00"}
```
Portus is being deployed via the offical helm chart. 

Here's the token portion of my nginx
```
 # Portus needs to handle /v2/token for authentication
        location = /v2/token {
          {{- if .Values.portus.tls.enabled }}
          proxy_pass https://{{ template "portus.fullname" . }};
          {{- else }}
          proxy_pass http://{{ template "portus.fullname" . }};
          {{- end }}

          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_read_timeout 900;
          proxy_buffering on;
        }
```

**Comment by Nick-Harvey** [comment]
FQDN is set correctly as well in the config

**Comment by Vad1mo** [comment]
I can confirm this. Everything is setup correctly. I generally can push pull  image. 
This node image was pushed by the user and it fails.  

```
2018-02-05T16:59:44.136162701Z Handling 'push' event:
2018-02-05T16:59:44.136225610Z {
2018-02-05T16:59:44.136243275Z   "id": "c27e93a7-a4f5-4a88-851e-f8931377eed6",
2018-02-05T16:59:44.136259625Z   "timestamp": "2018-02-05T16:56:50.253380461Z",
2018-02-05T16:59:44.136274864Z   "action": "push",
2018-02-05T16:59:44.136290303Z   "target": {
2018-02-05T16:59:44.136306022Z     "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
2018-02-05T16:59:44.136322775Z     "size": 2007,
2018-02-05T16:59:44.136338074Z     "digest": "sha256:021c1dba94d141972a13f62194fea0f8ef2a081cd9c03fd3f70a529886a8af11",
2018-02-05T16:59:44.136354103Z     "length": 2007,
2018-02-05T16:59:44.136368891Z     "repository": "vadim/node",
2018-02-05T16:59:44.136384611Z     "url": "https://docker.for.mac.localhost/v2/vadim/node/manifests/sha256:021c1dba94d141972a13f62194fea0f8ef2a081cd9c03fd3f70a529886a8af11",
2018-02-05T16:59:44.136400691Z     "tag": "latest"
2018-02-05T16:59:44.136416040Z   },
2018-02-05T16:59:44.136430838Z   "request": {
2018-02-05T16:59:44.136445815Z     "id": "df26123a-20d2-4479-b6c6-10cd02dad179",
2018-02-05T16:59:44.136461284Z     "addr": "84.72.104.165",
2018-02-05T16:59:44.136476452Z     "host": "docker.for.mac.localhost",
2018-02-05T16:59:44.136491680Z     "method": "PUT",
2018-02-05T16:59:44.136506829Z     "useragent": "docker/17.12.0-ce go/go1.9.2 git-commit/c97c6d6 kernel/4.9.60-linuxkit-aufs os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.0-ce \\(darwin\\))"
2018-02-05T16:59:44.136523351Z   },
2018-02-05T16:59:44.136538328Z   "actor": {
2018-02-05T16:59:44.136553456Z     "name": "vadim"
2018-02-05T16:59:44.136568304Z   },
2018-02-05T16:59:44.136583051Z   "source": {
2018-02-05T16:59:44.136598119Z     "addr": "492974b091b3:5000",
2018-02-05T16:59:44.136613237Z     "instanceID": "ae278fc6-9e2e-4ce1-9fa5-7b9b5f29a76e"
2018-02-05T16:59:44.136631934Z   }
2018-02-05T16:59:44.136647012Z }
2018-02-05T16:59:44.516430325Z Could not fetch manifest for 'vadim/node' with digest 'sha256:021c1dba94d141972a13f62194fea0f8ef2a081cd9c03fd3f70a529886a8af11': Cannot obtain authorization token: #<Net::HTTPBadGateway:0x000055f359267968>
2018-02-05T16:59:44.830970163Z /app/lib/portus/http_helpers.rb:120:in `request_auth_token': Cannot obtain authorization token: #<Net::HTTPBadGateway:0x000055f35805b198> (Portus::Errors::AuthorizationError)
2018-02-05T16:59:44.831366893Z 	from /app/lib/portus/http_helpers.rb:48:in `perform_request'
2018-02-05T16:59:44.831499377Z 	from /app/lib/portus/http_helpers.rb:63:in `safe_request'
2018-02-05T16:59:44.831700294Z 	from /app/lib/portus/registry_client.rb:58:in `manifest'
2018-02-05T16:59:44.831979257Z 	from /app/lib/portus/security.rb:46:in `vulnerabilities'
2018-02-05T16:59:44.832238932Z 	from /app/lib/portus/background/security_scanning.rb:39:in `block in execute!'
2018-02-05T16:59:44.832515710Z 	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
2018-02-05T16:59:44.832783525Z 	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
2018-02-05T16:59:44.833059962Z 	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
2018-02-05T16:59:44.833325723Z 	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
2018-02-05T16:59:44.833563332Z 	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
2018-02-05T16:59:44.833815728Z 	from /app/lib/portus/background/security_scanning.rb:27:in `execute!'
2018-02-05T16:59:44.834076927Z 	from /app/bin/background.rb:55:in `block (2 levels) in <top (required)>'
2018-02-05T16:59:44.834451000Z 	from /app/bin/background.rb:53:in `each'
2018-02-05T16:59:44.834766294Z 	from /app/bin/background.rb:53:in `block in <top (required)>'
2018-02-05T16:59:44.835034882Z 	from /app/bin/background.rb:52:in `loop'
2018-02-05T16:59:44.835311660Z 	from /app/bin/background.rb:52:in `<top (required)>'
2018-02-05T16:59:44.835575816Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
2018-02-05T16:59:44.835846369Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
2018-02-05T16:59:44.836103486Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
2018-02-05T16:59:44.841530701Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
2018-02-05T16:59:44.841599926Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
2018-02-05T16:59:44.841617712Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2018-02-05T16:59:44.841634774Z 	from /usr/local/bundle/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
2018-02-05T16:59:44.841651577Z 	from bin/rails:12:in `require'
2018-02-05T16:59:44.841667297Z 	from bin/rails:12:in `<main>'
2018-02-05T21:48:09.222802348Z [Mailer config] Host:     docker.for.mac.localhost
2018-02-05T21:48:09.222995356Z [Mailer config] Protocol: https://
2018-02-05T21:48:25.173797886Z [Initialization] Running: 'Registry events', 'Security scanning', 'Registry synchronization'
```

**Comment by mssola** [comment]
I was also able to reproduce this (similar logs)...

**Comment by Vad1mo** [comment]
here some more logs from the registry.

10.0.0.14  is background
10.0.0.18 is Portus

```
08T15:27:48+01:00" level=info msg="response completed" go.version=go1.7.6 http.request.host=docker.portus.local http.request.id=b22d029d-bed4-4efc-b9b5-d90c1991b4ee http.request.method=GET http.request.remoteaddr=10.255.0.4 http.request.uri="/v2/vadim/registry/manifests/latest" http.request.useragent=Ruby http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=337.67108ms http.response.status=200 http.response.written=1364 instance.id=45e4855a-57a9-42e8-b141-2300cc8aa525 version=v2.6.2 
2018-02-08T14:27:48.256903038Z 10.0.0.18 - - [08/Feb/2018:15:27:47 +0100] "GET /v2/vadim/registry/manifests/latest HTTP/1.1" 200 1364 "" "Ruby"
2018-02-08T14:27:48.281660541Z time="2018-02-08T15:27:48+01:00" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=docker.portus.local http.request.id=8df4edc5-574b-4eb4-ab4a-c2964da67fab http.request.method=GET http.request.remoteaddr=10.255.0.4 http.request.uri="/v2/vadim/ruby/manifests/latest" http.request.useragent=Ruby instance.id=45e4855a-57a9-42e8-b141-2300cc8aa525 vars.name="vadim/ruby" vars.reference=latest version=v2.6.2 
2018-02-08T14:27:48.281702610Z 10.0.0.14 - - [08/Feb/2018:15:27:48 +0100] "GET /v2/vadim/ruby/manifests/latest HTTP/1.1" 401 153 "" "Ruby"
2018-02-08T14:27:48.743046417Z time="2018-02-08T15:27:48+01:00" level=info msg="response completed" go.version=go1.7.6 http.request.host=docker.portus.local http.request.id=41cfd6c7-fda9-424c-9e68-1c34c2e3d0ba http.request.method=GET http.request.remoteaddr=10.255.0.4 http.request.uri="/v2/vadim/ruby/manifests/latest" http.request.useragent=Ruby http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=317.931395ms http.response.status=200 http.response.written=1154 instance.id=45e4855a-57a9-42e8-b141-2300cc8aa525 version=v2.6.2 
2018-02-08T14:27:48.743080546Z 10.0.0.18 - - [08/Feb/2018:15:27:48 +0100] "GET /v2/vadim/ruby/manifests/latest HTTP/1.1" 200 1154 "" "Ruby"
2018-02-08T14:27:56.873857312Z time="2018-02-08T15:27:56+01:00" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=docker.portus.local http.request.id=2d00b17f-4682-40ee-849d-b1d2d551c0f7 http.request.method=GET http.request.remoteaddr=10.255.0.4 http.request.uri="/v2/" http.request.useragent=Ruby instance.id=45e4855a-57a9-42e8-b141-2300cc8aa525 version=v2.6.2 
2018-02-08T14:27:56.873914297Z 10.0.0.14 - - [08/Feb/2018:15:27:56 +0100] "GET /v2/ HTTP/1.1" 401 87 "" "Ruby"
```

Just

**Comment by mnick-nm** [comment]
Just to share my experience - I'm deploying in kube cluster via our own internal pattern and this will happen to our background container logs when I bounce the portus pod, but it'll connect within a few minutes

**Comment by Nick-Harvey** [comment]
Can confirm, after a few minutes the token is indeed pulled correctly and the background process starts normally.

**Comment by mssola** [comment]
I just gave it another shot and it turns out my problem was that I was not configuring the `external_hostname` part properly.

For the others, I see that it was a momentary setback (which I should investigate for the 2.4 release...).  So, I will schedule this for 2.4 with the aim of:

- Better documentation.
- Improve the examples (hopefully when the Helm chart is finally released we can get a more realistic use case).
- Fixing any minor issues with the token not being ready when the background job starts.

**Comment by tankbusta** [comment]
@mssola Sorry, but was there a solution for this? I'm getting the same error (it crashes the background worker). I'm not sure if `external_hostname` is a configurable property?

**Comment by mssola** [comment]
So, after going through this issue again, I've decided to postpone it for the `2.5` release since:

- The image is stable now and the points discussed [here](https://github.com/SUSE/Portus/issues/1624#issuecomment-368920982) have been mostly addressed.
- There's a described workaround.
- In `2.5` providing a stable Helm chart will be top priority. This means that:
  - The Helm chart that I've talked here and there will be provided shortly after we start the development of `2.5` (which should happen sooner rather than later, considering that we may release `2.4` next week).
  - This issue, and similar issues that have been submitted, will be fixed once we submit this Helm chart because we will re-evaluate these issues when providing the Helm chart.
  - We will provide better documentation on the common pitfalls on all these scenarios.
- Note that there are efforts of a stable Helm chart [here](https://github.com/helm/charts/pull/2766) as well.

Sorry for any inconvenience.

**Comment by shreelola** [comment]
what's the described workaround for this issue? I"m still seeing this issue on 2.4 image

**Comment by anacelto** [comment]
Me too...
