### ISSUE TITLE
Portus communication w/ registry | request error (NoMethodError)

### ISSUE THREAD

**Issue by soosap** [SUSE/Portus#1701]
* After initialization I am able to create an admin user and to enter my private registry.
* I only use tls encryption at the loadbalancer level, not inside portus and not inside registry either
* As **Hostname** I use `registry-registry.default.svc.cluster.local:5000` (SSL not turned on). I am greeted with `Registry was successfully created`
* Then when I continue to navigate around, no matter what I click in the UI the following error is being thrown in the portus background container which was started w/ `PORTUS_BACKGROUND` being set to **true**

I suspect that I may have configured the registry incorrectly. Can you help me understand this error message? How can I test whether token based authentication on the registry is set up correctly?

```
Failed to create bus connection: No such file or directory
[Mailer config] Host:     registry-portus
[Mailer config] Protocol: https://
Failed to create bus connection: No such file or directory
[Initialization] Running: 'Registry events', 'Security scanning', 'Registry synchronization'
  RegistryEvent Load (0.3ms)  SELECT  "registry_events".* FROM "registry_events" WHERE "registry_events"."status" = $1  ORDER BY "registry_events"."id" ASC LIMIT 1000  [["status", 2]]
  Registry Load (0.4ms)  SELECT  "registries".* FROM "registries"  ORDER BY "registries"."id" ASC LIMIT 1000
/usr/lib64/ruby/2.5.0/net/http/generic_request.rb:20:in `initialize': undefined method `request_uri' for #<URI::Generic:0x0000000004df76a0> (NoMethodError)
	from /usr/lib64/ruby/2.5.0/net/http/request.rb:15:in `initialize'
	from /srv/Portus/lib/portus/http_helpers.rb:112:in `new'
	from /srv/Portus/lib/portus/http_helpers.rb:112:in `request_auth_token'
	from /srv/Portus/lib/portus/http_helpers.rb:48:in `perform_request'
	from /srv/Portus/lib/portus/registry_client.rb:131:in `get_page'
	from /srv/Portus/lib/portus/registry_client.rb:118:in `paged_response'
	from /srv/Portus/lib/portus/registry_client.rb:83:in `catalog'
	from /srv/Portus/lib/portus/background/sync.rb:25:in `block in execute!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
	from /srv/Portus/lib/portus/background/sync.rb:24:in `execute!'
	from /srv/Portus/bin/background.rb:55:in `block (2 levels) in <top (required)>'
	from /srv/Portus/bin/background.rb:53:in `each'
	from /srv/Portus/bin/background.rb:53:in `block in <top (required)>'
	from /srv/Portus/bin/background.rb:52:in `loop'
	from /srv/Portus/bin/background.rb:52:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'
RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/background.rb
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/cli.rb:258:in `exec'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
```

Here is my nginx configuration
```
    # This file is largely based on the one written by @Djelibeybi in:
    #      https://github.com/Djelibeybi/Portus-On-OracleLinux7/
    events {
      worker_connections 1024;
    }
    http {
      default_type  application/octet-stream;
      charset       UTF-8;
      # Some basic config.
      server_tokens off;
      sendfile      on;
      tcp_nopush    on;
      tcp_nodelay   on;
      # On timeouts.
      keepalive_timeout     65;
      client_header_timeout 240;
      client_body_timeout   240;
      fastcgi_read_timeout  249;
      reset_timedout_connection on;
      ## Set a variable to help us decide if we need to add the
      ## 'Docker-Distribution-Api-Version' header.
      ## The registry always sets this header.
      ## In the case of nginx performing auth, the header will be unset
      ## since nginx is auth-ing before proxying.
      map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
        '' 'registry/2.0';
      }
      upstream registry-portus {
        least_conn;
        server registry-portus:3000 max_fails=3 fail_timeout=15s;
      }
      upstream registry-registry:30000 {
        least_conn;
        server registry-registry:30000 max_fails=3 fail_timeout=15s;
      }
      server {
        server_name registry-nginx
        listen 80 http2;
        ##
        # Docker-specific stuff.
        proxy_set_header Host $http_host;   # required for Docker client sake
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        # disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;
        # required to avoid HTTP 411: see Issue #1486
        # (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;
        ##
        # Custom headers.
        # Adding HSTS[1] (HTTP Strict Transport Security) to avoid SSL stripping[2].
        #
        # [1] https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
        # [2] https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        # Don't allow the browser to render the page inside a frame or iframe
        # and avoid Clickjacking. More in the following link:
        #
        # https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options
        add_header X-Frame-Options DENY;
        # Disable content-type sniffing on some browsers.
        add_header X-Content-Type-Options nosniff;
        # This header enables the Cross-site scripting (XSS) filter built into
        # most recent web browsers. It's usually enabled by default anyway, so the
        # role of this header is to re-enable the filter for this particular
        # website if it was disabled by the user.
        add_header X-XSS-Protection "1; mode=block";
        # Add header for IE in compatibility mode.
        add_header X-UA-Compatible "IE=edge";

        # Redirect (most) requests to /v2/* to the Docker Registry
        location /v2/ {
          # Do not allow connections from docker 1.5 and earlier
          # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
          if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
            return 404;
          }
          ## If $docker_distribution_api_version is empty, the header will not be added.
          ## See the map directive above where this variable is defined.
          add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;
          proxy_pass http://registry-registry:30000;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }

        # Portus needs to handle /v2/token for authentication
        location = /v2/token {
          proxy_pass http://registry-portus;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }

        # Portus needs to handle /v2/webhooks/events for notifications
        location = /v2/webhooks/events {
          proxy_pass http://registry-portus;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }

        # Portus handles everything else for the UI
        location / {
          try_files $uri/index.html $uri.html $uri @registry-portus;
        }

        location @registry-portus {
          proxy_pass http://registry-portus;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }
      }
    }
```

**Comment by Vad1mo** [comment]
You have to setup the DB in utf8.

Check this for reference
```
command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
```

its from `docker-compose.yml` in the portus root

**Comment by soosap** [comment]
It seems like UTF8 is default for the postgres docker image. Do you have some more ideas what could cause this error?

```
portus=# SHOW client_encoding;
 client_encoding
-----------------
 UTF8
(1 row)

portus=# SHOW server_encoding;
 server_encoding
-----------------
 UTF8
(1 row)
```

**Comment by soosap** [comment]
I think I got closer to the problem, thanks for pointing into the database direction.

So here is what happens, my postgres container initializes on startup and just keeps on listening...

```
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
CREATE DATABASE

CREATE ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2018-02-22 21:38:57 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```
Then for a while nothing happens and then this is being printed:
```
ERROR:  database "portus" already exists
STATEMENT:  CREATE DATABASE "portus" ENCODING = 'utf8'
```
Not sure if this is just a warning or the root cause of the problem.

**Comment by soosap** [comment]
I can confirm the database is not the problem, postgres works with portus w/o issues.
```
$ portusctl exec rake db:create
$ portusctl exec rake db:migrate
$ portusctl exec rake db:seed
$ portusctl exec rails r bin/check_db.rb
```
I executed those commands just to be sure, but postgres has been already created, migrated and seeded automatically. It is also in the `DB_READY` state. I looked into the database and saw all the tables being created. Most databases were empty but the `users` database for instance contained an entry for the special `portus` user.

### Communication between portus and registry

So my investigation led me to the conclusion that **portus** may not be able to properly communicate with the **registry**.
```
time="2018-02-23T09:06:40.035672848Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host="registry-registry.default.svc.cluster.local:5000" http.request.id=0bd0e206-3759-42b6-a979-60b8140db59b http.request.method=GET http.request.remoteaddr="100.96.3.163:44116" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=b562192d-409d-4d8c-8aef-af5aadd33875 version=v2.6.2
time="2018-02-23T09:06:40.035819672Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="registry-registry.default.svc.cluster.local:5000" http.request.id=0bd0e206-3759-42b6-a979-60b8140db59b http.request.method=GET http.request.remoteaddr="100.96.3.163:44116" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=b562192d-409d-4d8c-8aef-af5aadd33875 version=v2.6.2
100.96.3.163 - - [23/Feb/2018:09:06:40 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
```
In particular, portus is trying to fetch the catalog of images from the registry but it is unsuccessful as it is not authorized to get a hold of that data.

The setup that I have is **nginx** (serviceName: registry-nginx) in the front, **puma/portus** (serviceName: registry-portus) and **registry** (serviceName: registry-registry) behind it.

```
bash-4.3# curl registry-nginx/v2/token
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkgzRVU6RlJRQTo3QU9LOkdYM0s6RFdGNzpBSEhDOk5ZVU86TEFFRzpRSUtFOkpQRUs6Mlk0WjpFNTRJIn0.eyJpc3MiOiJyZWdpc3RyeS1wb3J0dXMiLCJzdWIiOm51bGwsImF1ZCI6bnVsbCwiaWF0IjoxNTE5Mzc4NjczLCJuYmYiOjE1MTkzNzg2NjgsImV4cCI6MTUxOTM3ODk3MywianRpIjoicjJ5ZTRzTUZhUHR1bUROV3VxZFZIclJoenBlVWdrcXlMbXNIRHM0b0VoIiwiYWNjZXNzIjpbXX0.IqzYOPzJQ-7pZOFPq8V578fq1tnLXdo_xWW24SxcYnQRdcdNUMwCyF64zhjuGEDnkWhmDkieVoZDIlBGLz8K2aN0BVAPa4HvIbq0NTuUgScPqHeqM98AzvE5eK8Uc55VF1Ut4QuM_ji3J8aOMPoaZGpEFYKMGz4UCvVpyolrEf8JWYRrz1cMKMDW4kKG5aMzXlv8l0WQD8WMLIyXSDTKUZ4WWpcjU0Ms8rsUy4BvnslGbV0xJPK-irV-MpC0aGEujaYqzl9O7DPhaL5g4DKjy90mq4c6gprzVrmq9bv53JJkOfu48Pbw3dqNblIfYfFdnUy-g5L3woeIR9Mhn7quSA","expires_in":300,"issued_at":"2018-02-23T09:37:53+00:00"}
```

```
bash-4.3# curl registry-nginx/v2/_catalog
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
```

**How to make use of the token?**

**How to tell registry-portus to make use of the token such that it is authorized to ask for `GET /v2/_catalog?n=100`?**

Sorry if these are beginner type of questions... :)
