### ISSUE TITLE
Devise.secret_key was not set

### ISSUE THREAD

**Issue by soosap** [SUSE/Portus#1884]
Hi there, I am trying to run `v2.3` of portus. I believe that after the upgrade to ruby 2.5 the following problem emerged. Anything that I miss here?

```
/srv/Portus/config/initializers/draw_def.rb:5:in `instance_eval': Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

  config.secret_key = '8d84321b45f51b879f92585e55199be096cd4b7b783ce87f88a3277b699873e5ad9525e40293f91037e3f18b63b6ea68dee96de9d57d12a28a76888780322fb3'

Please ensure you restarted your application after installing Devise or setting the key.
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/devise-4.4.0/lib/devise/rails/routes.rb:228:in `devise_for'
	from (eval):3:in `draw'
	from /srv/Portus/config/initializers/draw_def.rb:5:in `instance_eval'
	from /srv/Portus/config/initializers/draw_def.rb:5:in `draw'
	from /srv/Portus/config/routes.rb:4:in `block (2 levels) in <top (required)>'
	from /srv/Portus/config/routes.rb:4:in `each'
	from /srv/Portus/config/routes.rb:4:in `block in <top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /srv/Portus/config/routes.rb:3:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:170:in `reload_routes!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/devise-4.4.0/lib/devise/rails.rb:17:in `block in <class:Engine>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:55:in `block in <module:Finisher>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib64/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib64/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib64/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib64/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `each'
	from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `call'
	from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib64/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /usr/lib64/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
	from /srv/Portus/config/environment.rb:7:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:52:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'
RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/check_db.rb
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/cli.rb:286:in `exec'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
Failed to create bus connection: No such file or directory
/srv/Portus/config/initializers/draw_def.rb:5:in `instance_eval': Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

  config.secret_key = 'f70836fa65112a1877e9d1c694ad4ca398679e34a3a1e57ee61604225fcbaea0e8e427cb8f2e69d998364b3ee40bae342ab4ddbe74e6d90e0c8b157b7209f3ac'

Please ensure you restarted your application after installing Devise or setting the key.
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/devise-4.4.0/lib/devise/rails/routes.rb:228:in `devise_for'
	from (eval):3:in `draw'
	from /srv/Portus/config/initializers/draw_def.rb:5:in `instance_eval'
	from /srv/Portus/config/initializers/draw_def.rb:5:in `draw'
	from /srv/Portus/config/routes.rb:4:in `block (2 levels) in <top (required)>'
	from /srv/Portus/config/routes.rb:4:in `each'
```

**Comment by soosap** [comment]
I tried to set the **Devise Secret Key** but was not successful at it. I have checked in the source under `Portus/config/initializers/devise.rb`

```
# Use this hook to configure devise mailer, warden hooks and so forth.
# Many of these configuration options can be set straight in your model.
Devise.setup do |config|
  # The secret key used by Devise. Devise uses this key to generate
  # random tokens. Changing this key will render invalid all existing
  # confirmation, reset password and unlock tokens in the database.
  # config.secret_key = 'randomstring'
```

It seems the Devise secret key is not set and there is no way to set this when using the Portus Docker Image. Can you confirm this?

**Comment by vitoravelino** [comment]
I would suggest you to revert these secret changes you've and restart the container.

If you could share how was your upgrade process maybe we could have some insight.

**Comment by soosap** [comment]
Hi Vito, I am very sorry for the false alarm. I have enabled rbac on my kubernetes cluster. Then because certain permissions were not available secrets were not properly populated into the container. The above error occurred because PORTUS_SECRET_KEY_BASE was not set. I was convinced that it was set, but digging into all directions revealed that this was related to rbac. Thanks for offering to help :)
