### ISSUE TITLE
problem with background service registry auth

### ISSUE THREAD

**Issue by fragpit** [SUSE/Portus#1899]
### Description

trying to deploy docker-compose.insecure.yml for testing. 
stuck with failing background service.

```
7.6 http.request.host="registry:5000" http.request.id=04c223de-4e15-4523-801e-95b5afb7071c http.request.method=GET http.request.remoteaddr="172.22.0.5:35394" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=f38f08c7-3d93-44ae-a4fb-b453c48a3e83 version=v2.6.2
registry_1    | 172.22.0.5 - - [24/Jul/2018:13:32:18 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
portus_1      | Started GET "/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=172.17.42.1%3A5000" for 172.22.0.1 at 2018-07-24 13:32:18 +0000
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"172.17.42.1:5000"}
portus_1      | Completed 200 OK in 206ms (Views: 0.5ms | ActiveRecord: 7.9ms)
registry_1    | time="2018-07-24T13:32:19Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host="registry:5000" http.request.id=accdafcc-03e9-4987-a5ae-84e019bd53d7 http.request.method=GET http.request.remoteaddr="172.22.0.5:35402" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=f38f08c7-3d93-44ae-a4fb-b453c48a3e83 version=v2.6.2
registry_1    | 172.22.0.5 - - [24/Jul/2018:13:32:19 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
background_1  | 	from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
background_1  | 	from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
background_1  | 	from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
```

### Steps to reproduce

1. clone https://github.com/SUSE/Portus and checkout to 2.3.3
2. modify .env `MACHINE_FQDN=172.17.42.1`
3. modify mariadb tag in docker-compose.yml to 10.0.35
4. run docker-compose -f docker-compose.insecure.yml up -d
5. And this happened!

also i'm unable to push

```
# docker push 172.17.42.1:5000/admin/registry:latest
The push refers to repository [172.17.42.1:5000/admin/registry]
00b6cd9831d7: Preparing
5030e231e2c6: Preparing
7a2efe6c629c: Preparing
f824ed3a5fe3: Preparing
4da3a15c1916: Preparing
denied: requested access to the resource is denied
```

with log:

```
registry_1    | time="2018-07-24T13:40:59Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="172.17.42.1:5000" http.request.id=adb8e111-0bd5-4ced-b1be-d61dff387113 http.request.method=GET http.request.remoteaddr="172.22.0.1:39948" http.request.uri="/v2/" http.request.useragent="docker/18.03.1-ce go/go1.9.5 git-commit/9ee9f40 kernel/4.17.0-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))" instance.id=f38f08c7-3d93-44ae-a4fb-b453c48a3e83 version=v2.6.2
registry_1    | 172.22.0.1 - - [24/Jul/2018:13:40:59 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/18.03.1-ce go/go1.9.5 git-commit/9ee9f40 kernel/4.17.0-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))"
portus_1      | Started GET "/v2/token?account=admin&scope=repository%3Aadmin%2Fregistry%3Apush%2Cpull&service=172.17.42.1%3A5000" for 172.22.0.1 at 2018-07-24 13:40:59 +0000
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"admin", "scope"=>"repository:admin/registry:push,pull", "service"=>"172.17.42.1:5000"}
portus_1      | Completed 200 OK in 196ms (Views: 0.5ms | ActiveRecord: 6.1ms)
registry_1    | time="2018-07-24T13:40:59Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host="172.17.42.1:5000" http.request.id=23bea257-7c88-484f-b7ab-efc8f63acc0b http.request.method=HEAD http.request.remoteaddr="172.22.0.1:39956" http.request.uri="/v2/admin/registry/blobs/sha256:765973b0f65f59c7bc3139003337264d9f6c69938b94a05035a2c4e64f41d5fb" http.request.useragent="docker/18.03.1-ce go/go1.9.5 git-commit/9ee9f40 kernel/4.17.0-1.el7.elrepo.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))" instance.id=f38f08c7-3d93-44ae-a4fb-b453c48a3e83 vars.digest="sha256:765973b0f65f59c7bc3139003337264d9f6c69938b94a05035a2c4e64f41d5fb" vars.name="admin/registry" version=v2.6.2
```

**Comment by fragpit** [comment]
resolved using secure installation with nginx and same registry path as portus service. also changed portus container tags to 2.3 because head was broken.

**Comment by mssola** [comment]
>  looks like background service always fail when adding wrong registry

I'll close this issue, but I'll also investigate this before releasing 2.4. Thanks for the hint :+1:

**Comment by mssola** [comment]
I've tested this and when a Registry is badly configured, the exception is logged but the background process doesn't crash. So I'll mark this one as done, unless someone has an example configuration making the background process to crash.

**Comment by RjEcho217** [comment]
> I've tested this and when a Registry is badly configured, the exception is logged but the background process doesn't crash. So I'll mark this one as done, unless someone has an example configuration making the background process to crash.

What is an example of a badly configured registry?

**Comment by RedFlames** [comment]
Hello,
I'm not sure if I should open a new issue, but I've started running into this issue while testing portus via docker-compose. I'm using 2.4 images and my background container crashes repeatedly.

[docker-compose.yml.txt](https://github.com/SUSE/Portus/files/3591122/docker-compose.yml.txt)

Based this off [docker-compose.clair-ssl.yml](https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.clair-ssl.yml).

In `.env` I have the machine's IP in `MACHINE_FQDN`, and extended the two passwords to have >= 8 characters. I put in a new `SECRET_KEY_BASE` generated with `sudo docker run --entrypoint "portusctl" opensuse/portus:head exec rails secret` because I wasn't 100% clear on what it's needed for and if I need to put in my own random string or if it needs any sort of format. Haven't actually used rails before. :)

Generated certs in this way
```
echo "subjectAltName = IP:172.16.27.20" > extfile.cnf
openssl genrsa -out rootca.key 2048
openssl req -x509 -new -nodes -key rootca.key \
 -subj "/C=DE/ST=NRW" \
 -sha256 -days 1024 -out secrets/rootca.crt
openssl genrsa -out secrets/portus.key 2048
openssl req -new -key secrets/portus.key -out secrets/portus.csr \
 -subj "/C=DE/ST=NRW/CN=172.16.27.20"
openssl x509 -req -in secrets/portus.csr -CA secrets/rootca.crt -extfile \
 extfile.cnf -CAkey rootca.key -CAcreateserial \
 -out secrets/portus.crt -days 500 -sha256
```

In `registry/init` I added
```
[ -f /secrets/rootca.crt ] && cp /secrets/rootca.crt /usr/local/share/
```
before the `update-ca-certificates`.

and in the compose.yml I changed `REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/rootca.crt` so that webhooks go through.

[background_1_crash.txt](https://github.com/SUSE/Portus/files/3591180/background_1_crash.txt)

Relevant error line seems to be:
```
registry_1    | time="2019-09-09T14:38:18Z" level=info msg="token signed by untrusted key with ID: \"USNW:YQCE:PVVJ:S6T4:QAZI:7UAZ:VLOC:OOGE:BAXM:SFG2:AQHA:WHIJ\""
registry_1    | time="2019-09-09T14:38:18Z" level=warning msg="error authorizing context: invalid token" go.version=go1.7.6 http.request.host="172.16.27.20:5000" http.request.id=00d4b8ec-d7f2-49a5-af99-b49cdf94bd1a http.request.method=GET http.request.remoteaddr="172.24.0.1:46148" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=819087f0-f6e6-4aec-8617-44c7ff81e81c version=v2.6.2-14-ga66a4c3
registry_1    | 172.24.0.1 - - [09/Sep/2019:14:38:18 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
...
```
see attached file for full error log lines.

(Funny thing is I had this working the other day, except that my DB hadn't been initialized because of the standard "portus" PWs of <8 characters, where the Portus interface would then always say "Portus user does not exist!")
