### ISSUE TITLE
docker-compose up from git checkout does not create DB

### ISSUE THREAD

**Issue by huslage** [SUSE/Portus#237]
I did a fresh checkout of the repo. The application does not work out-of-the-box. There are no documents describing how to create the db.

When I hit the web interface, I get the following error (full compose logs):

```
db_1  | 150729 15:42:07 [Note] mysqld (mysqld 10.0.20-MariaDB-1~jessie-log) starting as process 1 ...
db_1  | 150729 15:42:07 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1  | 150729 15:42:07 [Note] InnoDB: The InnoDB memory heap is disabled
db_1  | 150729 15:42:07 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1  | 150729 15:42:07 [Note] InnoDB: Memory barrier is not used
db_1  | 150729 15:42:07 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1  | 150729 15:42:07 [Note] InnoDB: Using Linux native AIO
db_1  | 150729 15:42:07 [Note] InnoDB: Using CPU crc32 instructions
db_1  | 150729 15:42:07 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1  | 150729 15:42:07 [Note] InnoDB: Completed initialization of buffer pool
db_1  | 150729 15:42:07 [Note] InnoDB: Highest supported file format is Barracuda.
db_1  | 150729 15:42:07 [Note] InnoDB: 128 rollback segment(s) are active.
db_1  | 150729 15:42:07 [Note] InnoDB: Waiting for purge to start
db_1  | 150729 15:42:07 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.24-72.2 started; log sequence number 1616717
db_1  | 150729 15:42:07 [Note] Plugin 'FEEDBACK' is disabled.
db_1  | 150729 15:42:07 [Note] Server socket created on IP: '::'.
db_1  | 150729 15:42:08 [Note] Event Scheduler: Loaded 0 events
db_1  | 150729 15:42:08 [Note] Reading of all Master_info entries succeded
db_1  | 150729 15:42:08 [Note] Added new Master_info '' to hash table
db_1  | 150729 15:42:08 [Note] mysqld: ready for connections.
db_1  | Version: '10.0.20-MariaDB-1~jessie-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
web_1 | => Booting Thin
web_1 | => Rails 4.2.2 application starting in development on http://0.0.0.0:3000
web_1 | => Run `rails server -h` for more startup options
web_1 | => Ctrl-C to shutdown server
web_1 | Thin web server (v1.6.3 codename Protein Powder)
web_1 | Maximum connections set to 1024
web_1 | Listening on 0.0.0.0:3000, CTRL+C to stop
web_1 | 
web_1 | 
web_1 | Started GET "/" for 172.17.42.1 at 2015-07-29 15:43:03 +0000
web_1 | Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
db_1  | 150729 15:43:03 [Warning] IP address '172.17.0.8' could not be resolved: Name or service not known
web_1 | 
web_1 | ActiveRecord::NoDatabaseError (Unknown database 'portus_development'):
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/mysql2_adapter.rb:23:in `rescue in mysql2_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/mysql2_adapter.rb:10:in `mysql2_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
web_1 |   /usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
web_1 |   /usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
web_1 |   activerecord (4.2.2) lib/active_record/connection_handling.rb:87:in `connection'
web_1 |   activerecord (4.2.2) lib/active_record/migration.rb:384:in `connection'
web_1 |   activerecord (4.2.2) lib/active_record/migration.rb:371:in `call'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
web_1 |   activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
web_1 |   activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
web_1 |   activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
web_1 |   activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web_1 |   web-console (2.1.3) lib/web_console/middleware.rb:29:in `call'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
web_1 |   railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
web_1 |   railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
web_1 |   activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
web_1 |   activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
web_1 |   activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
web_1 |   railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
web_1 |   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
web_1 |   rack (1.6.2) lib/rack/methodoverride.rb:22:in `call'
web_1 |   rack (1.6.2) lib/rack/runtime.rb:18:in `call'
web_1 |   activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
web_1 |   rack (1.6.2) lib/rack/lock.rb:17:in `call'
web_1 |   actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
web_1 |   rack (1.6.2) lib/rack/sendfile.rb:113:in `call'
web_1 |   railties (4.2.2) lib/rails/engine.rb:518:in `call'
web_1 |   railties (4.2.2) lib/rails/application.rb:164:in `call'
web_1 |   rack (1.6.2) lib/rack/content_length.rb:15:in `call'
web_1 |   thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
web_1 |   thin (1.6.3) lib/thin/connection.rb:84:in `catch'
web_1 |   thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
web_1 |   thin (1.6.3) lib/thin/connection.rb:53:in `process'
web_1 |   thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
web_1 |   eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
web_1 |   eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
web_1 |   thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
web_1 |   thin (1.6.3) lib/thin/server.rb:162:in `start'
web_1 |   rack (1.6.2) lib/rack/handler/thin.rb:19:in `run'
web_1 |   rack (1.6.2) lib/rack/server.rb:286:in `start'
web_1 |   railties (4.2.2) lib/rails/commands/server.rb:80:in `start'
web_1 |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:80:in `block in server'
web_1 |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:75:in `tap'
web_1 |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:75:in `server'
web_1 |   railties (4.2.2) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
web_1 |   railties (4.2.2) lib/rails/commands.rb:17:in `<top (required)>'
web_1 |   bin/rails:8:in `require'
web_1 |   bin/rails:8:in `<main>'
web_1 | 
web_1 | 
web_1 |   Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.3ms)
web_1 |   Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.5ms)
web_1 |   Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
web_1 |   Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (22.1ms)
```

**Comment by lsamayoa** [comment]
https://github.com/SUSE/Portus/wiki/The-development-environment

**Comment by huslage** [comment]
This doesn't fix the problem that the website says `docker-compose up` is
all I have to do to get started. I appreciate the link. t actually
bootstrapping this is pretty hard at the moment, and the site is misleading.

On Wed, Jul 29, 2015 at 1:01 PM, Flavio Castelli <notifications@github.com>
wrote:

> Closed #237 <https://github.com/SUSE/Portus/issues/237>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SUSE/Portus/issues/237#event-368562579>.
>



-- 
Aaron Huslage
+1-919-600-1712
IM: GTalk - huslage@gmail.com; Skype - huslage

PGP: 0x360DE590 / 30D4 B15B 74B2 F0E9 35D4  ABE0 2CB7 AC60 360D E590

**Comment by flavio** [comment]
I fixed the code snippet to include also the db related steps. We plan to write better documentation about how to run Portus using containers.

**Comment by huslage** [comment]
Awesome. Thanks!

On Wed, Jul 29, 2015 at 1:12 PM, Flavio Castelli <notifications@github.com>
wrote:

> I fixed the code snippet to include also the db related steps. We plan to
> write better documentation about how to run Portus using containers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SUSE/Portus/issues/237#issuecomment-126022149>.
>



-- 
Aaron Huslage
+1-919-600-1712
IM: GTalk - huslage@gmail.com; Skype - huslage

PGP: 0x360DE590 / 30D4 B15B 74B2 F0E9 35D4  ABE0 2CB7 AC60 360D E590
