### ISSUE TITLE
Docker setup not starting correctly

### ISSUE THREAD

**Issue by plamer** [SUSE/Portus#323]
Hello, 

I have troubles with getting the docker setup to work. After starting the containers with compose-setup.sh I get this:

    Cannot start container f107133ba6fafad4c6e8b50e81800c2da4eca782c3b27aed6c2a46ba9acc66ee: Cannot link to a non running container: /portus_web_1 AS /portus_registry_1/portus_web_1

My portus_web container exits with:

    /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find execjs-2.6.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:140:in `specs'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:185:in `specs_for'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:174:in `requested_specs'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:127:in `setup'
	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/local/bundle/bin/thin:14:in `<main>'

Am I doing something wrong? Thanks in advance!

**Comment by plamer** [comment]
Hm.. I guess just removing the docker image (portus_web) and building it from the Dockerfile again solved this.
