### ISSUE TITLE
docker/environment file missing. Basic install from Portus homepage broken.

### ISSUE THREAD

**Issue by kentoj** [SUSE/Portus#353]
Doing a git clone of the repo and a docker-compose up from the Portus directory causes an error of `Couldn't find env file: /Users/[username]/git/public/SUSE/Portus/docker/environment` on my machine. I looked at the repo and the docker/environment file is in fact missing. Am I supposed to copy one of the environment config files from the root config directory to docker/environment?

Whatever the matter, please update the installation instructions to enable the proper starting of Portus. I want to use it.

This is broken on Ubuntu 14.04 and Mac OS X Yosemite.

**Comment by mssola** [comment]
Hi @kentoj, as explained in the [wiki](https://github.com/SUSE/Portus/wiki/The-development-environment#docker), you have to use the `compose-setup.sh` script in order to setup your docker-compose workflow. The `docker/environment` file is created by this same script.

Feel free to comment on this issue if you have more questions regarding our docker-compose configuration.

**Comment by sopitz** [comment]
It's a similar issue that I run into on MacOS El Capitan: I try to run the `compose-setup.sh`and it gives the following error:
```bash
sopitz:Portus sopitz$ ./compose-setup.sh 
The setup will destroy the containers used by Portus, removing also their volumes.
Are you sure to delete all the data? (Y/N)Y
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 39, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 57, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 79, in get_project
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 62, in get_client
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docker_client", line 23, in docker_client
IndexError: list index out of range
```

Are there any tipps how to resolve that issue?
It's reproducable:
1) clone repository
2) run the `compose-setup.sh`
