### ISSUE TITLE
portusctl: Probably  setup --local-registry sets wrong value for rootcertbundle:

### ISSUE THREAD

**Issue by dukas** [SUSE/Portus#412]
Opensuse 13.2
Portus-20151008124708-1.1.x86_64
Documentation used: [Installing-Portus](https://github.com/SUSE/Portus/wiki/Installing-Portus)
```bash
portusctl setup --local-registry 
```
generated config.yml
```yaml
version: 0.1
loglevel: info
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /etc/registry/ssl.crt/portus.crt
    key: /srv/Portus/config/server.key

auth:
  token:
    realm: https://portus.domain.dom/v2/token
    service: portus.domain.dom:5000
    issuer: portus.domain.dom
    rootcertbundle: /etc/registry/ssl.crt/portus.crt

notifications:
  endpoints:
    - name: portus
      url: https://portus.domain.dom/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```
causes error, starting registry:
```bash
panic: unable to configure authorization (token): unable to parse token auth root certificate: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:257 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} tbsCertificate @4

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f8a89cc2778, 0xc820238450, 0xc820192d50, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/registry/handlers/app.go:188 +0x1df9
main.main()
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/cmd/registry/main.go:72 +0x6cf

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib64/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 34 [syscall]:
os/signal.loop()
        /usr/lib64/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib64/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 36 [runnable]:
fmt.(*fmt).writePadding(0xc820079b28, 0xf, 0xc820098050, 0x41, 0x41)
        /usr/lib64/go/src/fmt/format.go:100
fmt.(*fmt).padString(0xc820079b28, 0xc8200965a0, 0x1d)
        /usr/lib64/go/src/fmt/format.go:139 +0x2fb
fmt.(*fmt).fmt_s(0xc820079b28, 0xc8200965a0, 0x1d)
        /usr/lib64/go/src/fmt/format.go:322 +0x61
fmt.(*pp).fmtString(0xc820079ad0, 0xc8200965a0, 0x1d, 0xc800000073)
        /usr/lib64/go/src/fmt/print.go:521 +0xdc
fmt.(*pp).printArg(0xc820079ad0, 0x97d160, 0xc820072da0, 0x73, 0x0, 0x0)
        /usr/lib64/go/src/fmt/print.go:797 +0xd91
fmt.(*pp).doPrintf(0xc820079ad0, 0xc07d60, 0x18, 0xc820049a28, 0x4, 0x4)
        /usr/lib64/go/src/fmt/print.go:1219 +0x1dd8
fmt.Fprintf(0x7f8a89cc6a78, 0xc82006c0e0, 0xc07d60, 0x18, 0xc820049a28, 0x4, 0x4, 0xc81fffb4d0, 0x0, 0x0)
        /usr/lib64/go/src/fmt/print.go:188 +0x74
github.com/Sirupsen/logrus.(*TextFormatter).printColored(0xc820112020, 0xc82006c0e0, 0xc82027da00, 0xc8200965c0, 0x2, 0x2)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter.go:110 +0x38b
github.com/Sirupsen/logrus.(*TextFormatter).Format(0xc820112020, 0xc82027da00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/Godeps/_workspace/src/github.com/Sirupsen/logrus/text_formatter.go:78 +0x5ca
github.com/Sirupsen/logrus.(*Entry).Reader(0xc82027da00, 0xc806251904, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:41 +0x67
github.com/Sirupsen/logrus.(*Entry).log(0xc82027da00, 0x4, 0xc8200965a0, 0x1d)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:84 +0x25c
github.com/Sirupsen/logrus.(*Entry).Info(0xc82027da00, 0xc820049e20, 0x1, 0x1)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:119 +0x78
github.com/Sirupsen/logrus.(*Entry).Infof(0xc82027da00, 0xc06d00, 0x1b, 0xc820072d00, 0x1, 0x1)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/Godeps/_workspace/src/github.com/Sirupsen/logrus/entry.go:163 +0x139
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0x7f8a89cc6958, 0xc82027da00, 0x7f8a89cc6d28, 0xc82029a780, 0x7f8a89cc6cb8, 0xc82029ebe0, 0x2260ff9290000, 0xf3e500, 0x4e94914f0000)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/registry/handlers/app.go:806 +0x1a1
created by github.com/docker/distribution/registry/handlers.startUploadPurger
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/registry/handlers/app.go:814 +0x885

goroutine 37 [semacquire]:
sync.runtime_Syncsemacquire(0xc82027db90)
        /usr/lib64/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc82027db80)
        /usr/lib64/go/src/sync/cond.go:62 +0x9b
github.com/docker/distribution/notifications.(*eventQueue).next(0xc82011fb80, 0x0, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/notifications/sinks.go:203 +0xf6
github.com/docker/distribution/notifications.(*eventQueue).run(0xc82011fb80)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/notifications/sinks.go:174 +0x52
created by github.com/docker/distribution/notifications.newEventQueue
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/notifications/sinks.go:131 +0x1cb

goroutine 38 [select]:
github.com/docker/distribution/notifications.(*Broadcaster).run(0xc820282ff0)
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/notifications/sinks.go:80 +0x66c
created by github.com/docker/distribution/notifications.NewBroadcaster
        /home/abuild/rpmbuild/BUILD/docker-distribution-2.1.1/.gopath/src/github.com/docker/distribution/notifications/sinks.go:39 +0x100
```

If changed to 
```yaml
    rootcertbundle: /etc/apache2/ssl.crt/portus.domain.dom-ca.crt
```
Starts normally

**Update:**

Confirmed on clean install

**Comment by mssola** [comment]
Fixed with c41721bbb9a1cf3a5fb3f559c4bfa5e99cd80c1c. Thanks for reporting!
