### ISSUE TITLE
when starting Portus I get this error

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#806]
When I run the portus I get this error.

I run the **h0tbird/portus** image as there is no official one yet, 

usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `require': cannot load such file -- bigdecimal/util (LoadError)
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:4:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object/json.rb:4:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object.rb:12:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/configuration.rb:2:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/configuration.rb:2:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:2:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/railtie.rb:2:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:1:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:1:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:6:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:6:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails.rb:11:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails.rb:11:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/all.rb:1:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.2/lib/rails/all.rb:1:in `<top (required)>'
	from /portus/config/application.rb:3:in `require'
	from /portus/config/application.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /portus/config/environment.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from config.ru:3:in `block in <main>'

**Comment by Vad1mo** [comment]
I think the problem is part of the image https://hub.docker.com/r/h0tbird/portus/ that I used.
