### ISSUE TITLE
Portus does not handle delete webhooks/events. 

### ISSUE THREAD

**Issue by dforste** [SUSE/Portus#958]
Portus does not handle delete events. 
``` 
Started POST "/v2/webhooks/events" for 10.48.184.9 at 2016-07-07 06:11:37 +0000
Processing by Api::V2::EventsController#create as JSON
Handling 'delete' event:
{
  "id": "c13a2883-f2d5-4ec3-881c-33e42854997d",
  "timestamp": "2016-07-07T06:09:52.193178452Z",
  "action": "delete",
  "target": {
    "digest": "sha256:4a4aceb1fbd05888e565014dface338d92a3b028260dbce29ec160435b405860",
    "repository": "my_repo"
  },
  "request": {
    "id": "34840b7d-e2f9-41bf-b4a6-7079c8328519",
    "addr": "10.48.184.115",
    "host": "dockerhub.example.net",
    "method": "DELETE",
    "useragent": "Ruby"
  },
  "actor": {
    "name": "portus"
  },
  "source": {
    "addr": "a470a91e6c28:5000",
    "instanceID": "9516244b-63ad-45ee-bbd3-6dbe94562189"
  }
}
Completed 500 Internal Server Error in 30ms (ActiveRecord: 1.1ms)

NoMethodError (undefined method `handle_delete_event' for #<Class:0x007fc891abeda0>
Did you mean?  handle_push_event):
  lib/portus/registry_notification.rb:21:in `block (2 levels) in process!'
  lib/portus/registry_notification.rb:21:in `each'
  lib/portus/registry_notification.rb:21:in `block in process!'
  lib/portus/registry_notification.rb:13:in `each'
  lib/portus/registry_notification.rb:13:in `process!'
  app/controllers/api/v2/events_controller.rb:6:in `create'
```

**Comment by monstermunchkin** [comment]
Thanks for reporting this bug.
